language: go
go:
 - 1.1
 - 1.2
 - release
 - tip
before_install:
 - sudo add-apt-repository -y ppa:ubuntu/trusty/zeromq3
 - sudo apt-get update -qq
 - sudo apt-get install -y libzmq3-dev
install:
 - go get github.com/svenkreiss/databench_go/databench
 - go get -v ./...