language: go
go:
 - 1.1
 - 1.2
 - release
 - tip
before_install:
 - sudo apt-get update -qq
install:
 - sudo apt-get install libzmq3-dev
 - go get github.com/svenkreiss/databench_go/databench
 - go get -v ./...