language: go
go:
 - 1.1
 - 1.2
 - release
 - tip
before_install:
 - wget https://launchpad.net/ubuntu/+archive/primary/+files/libzmq3_4.0.4%2Bdfsg-2_i386.deb
 - sudo dpkg -i libzmq3_4.0.4+dfsg-2_i386.deb
install:
 - go get github.com/svenkreiss/databench_go/databench
 - go get -v ./...